// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4HzkNtUWLrDWvyJhJ11SaBKp82aaysR0',
    appId: '1:737349397921:web:d8fe1def5339e8fba26fe0',
    messagingSenderId: '737349397921',
    projectId: 'salama-attendance',
    authDomain: 'salama-attendance.firebaseapp.com',
    storageBucket: 'salama-attendance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUyhxH1a6Rk000du4755uZHTjhL7WKol8',
    appId: '1:737349397921:android:2241270c6bdc9b88a26fe0',
    messagingSenderId: '737349397921',
    projectId: 'salama-attendance',
    storageBucket: 'salama-attendance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL0WP-JQqN8K5YPaF_OynOfPUBuLcB0_4',
    appId: '1:737349397921:ios:138d57a5e8167ef4a26fe0',
    messagingSenderId: '737349397921',
    projectId: 'salama-attendance',
    storageBucket: 'salama-attendance.firebasestorage.app',
    iosBundleId: 'com.salamadrc.terminal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL0WP-JQqN8K5YPaF_OynOfPUBuLcB0_4',
    appId: '1:737349397921:ios:138d57a5e8167ef4a26fe0',
    messagingSenderId: '737349397921',
    projectId: 'salama-attendance',
    storageBucket: 'salama-attendance.firebasestorage.app',
    iosBundleId: 'com.salamadrc.terminal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4HzkNtUWLrDWvyJhJ11SaBKp82aaysR0',
    appId: '1:737349397921:web:58dedafbcd2c54a7a26fe0',
    messagingSenderId: '737349397921',
    projectId: 'salama-attendance',
    authDomain: 'salama-attendance.firebaseapp.com',
    storageBucket: 'salama-attendance.firebasestorage.app',
  );
}
